Feature branch
Ellyboi/Portfolio pull request #4
Opened 2022-12-10 17:19 UTC by Ellyboi

Desktop portfolio website assignment

2022-12-10 18:45 UTC, Qoosim requested changes
#  *Status: Required Changes* :recycle: 
 
Hi @Ellyboi, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Highlights
-  No linter errors. :heavy_check_mark: 
-  Good README file. :heavy_check_mark: 
-  Correct GitHub Flow. :heavy_check_mark: 

![](https://camo.githubusercontent.com/56bcd754643682fcc078b66eaa7278dead6c9c5013595c875b4ddcbe0f0ef0aa/68747470733a2f2f6d65646961302e67697068792e636f6d2f6d656469612f78554f786668365a4d373565664d3342716f2f67697068792d646f776e73697a65642d6d656469756d2e676966)


## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

- [ ] Kindly look into your mobile version of the project. I think while trying to style your project for the desktop version, you unintentionally broke some layout which you also need to revisit for proper re-styling. 
[your-mobile.webm](https://user-images.githubusercontent.com/26597432/206870476-549b5d18-55d4-4d53-8ab4-008d63bca7db.webm)

- [NOTE] Regarding your additional information on the pull request. You need not to worry yourself too much about repeating the week. What you should much more concern about is your understanding towards what you're learning. If by one reason or the other, you repeat the week, it is an opportunity to relearn what you've learned and doing so would definitely solidify your solid on those areas. Please, take your time to perfect your project before moving on. _**No need to rush**_

2022-12-10 18:45 UTC, Qoosim commented on index.html
>                <button class="projects1">See project</button>
- [ ] Good job so far. However, there are few things you need to work on before you move on. The information about the first project under my work is missing on your design. Kindly look into it and fix. Please, take a look

### Your Design
![your-first-work](https://user-images.githubusercontent.com/26597432/206869724-5643e566-95e8-4f56-b664-b69f3da3f2d3.png)

### Figma Design
![figma-first-work](https://user-images.githubusercontent.com/26597432/206869734-992723cb-9449-445f-b6cb-ae69684ef0a6.png)

2022-12-10 18:45 UTC, Qoosim commented on index.html
>          <div class="box2">
- [ ] There are overlapping of texts and images here. Kindly look into them and fix them. Please, take a look.

### Your Design
![your-second-work](https://user-images.githubusercontent.com/26597432/206869815-08ecf482-e25b-4842-9032-21f67ee81e3e.png)

### Figma Design
![figma-second-work](https://user-images.githubusercontent.com/26597432/206869828-00f644f3-8166-4c1e-ac0e-0b15c82aa0b8.png)

2022-12-10 18:45 UTC, Qoosim commented on index.html
>                                 <!--ABOUT ME SECTION-->
- [ ] The background image under your `about me` section is not properly positioned and that has created unwanted space to the right of the section. Kindly look into it and fix.

### Your Design
[your-about-me.webm](https://user-images.githubusercontent.com/26597432/206869994-ddf8143c-b560-43b5-99d7-f6cc7e8f9931.webm)

### Figma Design
![figma-about-me](https://user-images.githubusercontent.com/26597432/206870007-5153194a-aa93-4723-af65-1063e0bb7876.png)

2022-12-10 18:45 UTC, Qoosim commented on index.html
>              <li class="lang2">Ruby on Rails</li>
- [ ] The same thing that affected your about me section also affects this section. Kindly look into the unwanted space to the right of the section and remove it so as to make your project match the guiding template. You also need to work on the alignment of the list of languages and frameworks so as to look exactly like how they appear on the figma design.

### Your Design
[your-lang-frame.webm](https://user-images.githubusercontent.com/26597432/206870141-42271d2e-30ad-42e0-9625-61d272dcc94a.webm)

### Figma Design
![figma-lang-frame](https://user-images.githubusercontent.com/26597432/206870148-7d59b4e8-2da5-4204-acd1-e7074c07cfaa.png)

2022-12-10 18:45 UTC, Qoosim commented on index.html
>            </div>
- [ ] Same thing with this section. Kindly look into the unwanted space by the right of the section and remove it.

### Your Design
[your-contact-section.webm](https://user-images.githubusercontent.com/26597432/206870322-c991e505-bf34-41d7-ab66-0257b1fa1f0d.webm)

### Figma Design
![figma-contact-section](https://user-images.githubusercontent.com/26597432/206870336-7fd1d6f4-81d2-424a-98a9-1df5bc1c60f7.png)

2022-12-15 04:14 UTC, abdulhamiid requested changes
# Status: Required Changes :recycle:
Hi @Ellyboi , 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, I really appreciate the effort you put in! but there are still some which haven't been addressed yet.

![Alt Text](https://c.tenor.com/vOLW_UQMySIAAAAC/almost-there.gif)

## Highlights 🌟

- ✔️ Pull request description is descriptive
- ✔️ Linters checks are passing
- ✔️ Use GitHub Flow
- ✔️ Meaningful commit messages.

## Required Changes ♻️
_Please kindly check the comments under the review._

## Optional suggestions 🤷‍♂️
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

## Important Notes 📝
- Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
- Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-12-15 04:14 UTC, abdulhamiid commented on index.html
> +                  </form>
Please kindly arrange the form input element the way they appear in Figma so as to replicate the design because the alignment here is different from the given template 😒.


Your design
![image](https://user-images.githubusercontent.com/78251927/207764046-20d765b6-1e84-4c2c-afa1-529f40274c96.png)

Figma design
![image](https://user-images.githubusercontent.com/78251927/207764155-fac58fda-4a9c-4468-aa7c-ddcc9cc28d39.png)

2022-12-15 04:14 UTC, abdulhamiid commented on index.html
> +
Good card arrangement 👍 
![image](https://user-images.githubusercontent.com/78251927/207764898-a7859406-f332-4780-8e58-4ff41d9d9bc5.png)

When `hover` over the project cards,  in your design, the "See Project" button disappeared, please let's look into that and fix it.
![image](https://user-images.githubusercontent.com/78251927/207765111-a9cb3b5f-4d0c-4d69-ae8c-5e4bbf28bc49.png)

Figma 
![image](https://user-images.githubusercontent.com/78251927/207765241-8b5c9712-b113-4c1a-8eb7-68f07f1a39d2.png)

2022-12-15 04:14 UTC, abdulhamiid commented on index.html
> +=======
Please kindly consider removing this section. the section is duplicated and affects the live production, this usually happens when resolving a merge conflict. 

![image](https://user-images.githubusercontent.com/78251927/207766245-30ddaaca-1f54-4efa-bad6-cb53f3a68eaa.png)

2022-12-15 04:14 UTC, abdulhamiid commented on index.html
> -          <div class="box1">
Please consider removing the duplicate part of this section as it is affecting the design, this section is appearing twice in your design the other layout is perfect but you will need to remove this one.

Wrong {kindly remove)
![image](https://user-images.githubusercontent.com/78251927/207767227-cc3b72ae-4036-4d01-9985-ed988398ab83.png)

Correct layout ✔️ 
![image](https://user-images.githubusercontent.com/78251927/207767552-4bd18cc7-7a1a-44a9-813b-d24ef2ddb05c.png)

**Important**
When you finish working on the desktop design, kindly check also that the mobile design still looks like expected 😊

2022-12-15 04:14 UTC, abdulhamiid commented on style.css
> +/* stylelint-disable no-duplicate-selectors */
Kindly remove the commented codes. [Stylelint](https://stylelint.io/) is a linter for your stylesheets that helps you avoid errors and enforce conventions. please let's not try to bypass them

You can run `npx stylelint "**/*.{css,scss}" --fix` to automatically fix the stylelint errors in you CSS. 👽

If you will need an additional explanation or support please, kindly visit [this FAQ](https://microverse.zendesk.com/hc/en-us/articles/360026625973-How-can-I-get-help-from-TSEs-) to set up a 1:1 meeting with the Senior code reviewer. 😊

2022-12-15 12:32 UTC, Olamarx approved these changes
Hi @Ellyboi,

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 
<img src="https://media0.giphy.com/media/3oz8xAFtqoOUUrsh7W/giphy.gif"/>
## Highlights
- Linters passed ✔️ 
- Media Query ✔️ 

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-12-15 12:35 UTC, merged

2023-02-21 15:07 UTC, frank1738 reviewed
Hi @Ellyboi , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

<img src="https://media4.giphy.com/media/J8FZIm9VoBU6Q/giphy.gif"/>

## Highlights

✅ Correct use of Github workflow
✅ No linter error
✅ Good Design👍 


## Optional suggestions

N/A

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._